server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
        - id: room-service
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/room-service/**
        - id: video-service
          uri: lb://VIDEO-SERVICE
          predicates:
            - Path=/video-service/**


#springdoc:
#  api-docs:
#    enabled: true
#    path: /api-docs
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html
#  group-configs:
#    - group: user-service
#      paths-to-match: /user-service/**
#    - group: room-service
#      paths-to-match: /room-service/**
#    - group: video-service
#      paths-to-match: /video-service/**

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    urls:
      - name: User Service
        url: /user-service/api-docs
      - name: Room Service
        url: /room-service/api-docs
      - name: Video Service
        url: /video-service/api-docs





