apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: aniket9518/apigateway:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /config
        env:
        - name: SPRING_CONFIG_LOCATION
          value: "file:/config/"
      volumes:
      - name: config-volume
        configMap:
          name: studywiz-config
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: default  # Change if using a different namespace
spec:
  type: NodePort
  ports:
    - port: 80              # Port exposed by the service
      targetPort: 3000      # Port on which the app is running in the container
      nodePort: 30001       # Specify a NodePort (optional, else it'll be assigned automatically)
  selector:
    app: react-app          # Make sure this matches your deployment's labels

