apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka-server
  namespace: default
spec:
  selector:
    matchLabels:
      app: eureka-server 
  serviceName: "eureka-server"
  replicas: 1 
  template:
    metadata:
      labels:
        app: eureka-server 
    spec:
      containers:
      - name: eureka-server
        image: aniket9518/eurekaserver
        ports:
        - containerPort: 8761
        volumeMounts:
        - name: config-volume
          mountPath: /config
        env:
        - name: SPRING_CONFIG_LOCATION
          value: "file:/config/"
      volumes:
      - name: config-volume
        configMap:
          name: studywiz-config  
        
---

apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: default
spec:
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: eureka-server
