apiVersion: apps/v1
kind: Deployment
metadata:
  name:  react-app
  namespace: default
  labels:
    app:  react-app
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 1
  template:
    metadata:
      labels:
        app:  react-app
    spec:
      containers:
      - name:  react-app
        image:  aniket9518/studywizapp:latest
        ports:
        - containerPort: 5173


---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: default  # Change if using a different namespace
spec:
  type: NodePort
  ports:
    - port: 80              # Port exposed by the service
      targetPort: 5173      # Port on which the app is running in the container
      nodePort: 30001       # Specify a NodePort (optional, else it'll be assigned automatically)
  selector:
    app: react-app          # Make sure this matches your deployment's labels
