server:
  port: 8091

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com/postgres
    username: postgres.qvypkvgcdpirrncmgtte
    password: Aniket@8195
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  cloud:
#    discovery:
#      client:
#        serviceUrl:
#          defaultZone: http://localhost:8761/eureka/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
    path: /user-service/api-docs
  swagger-ui:
    enabled: true
    path: /user-service/swagger-ui.html

