server:
  port: 8092

spring:
  codec:
    max-in-memory-size: 10MB
  application:
    name: room-service
  datasource:
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com/postgres
    username: postgres.qvypkvgcdpirrncmgtte
    password: Aniket@8195
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  cloud:
#    discovery:
#      client:
#        serviceUrl:
#          defaultZone: http://localhost:8761/eureka/

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.defaultZone}

springdoc:
  api-docs:
    enabled: true
    path: /room-service/api-docs
  swagger-ui:
    enabled: true
    path: /room-service/swagger-ui.html


