name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push apigateway Image
        uses: docker/build-push-action@v4
        with:
          context: ./apiGateway
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/apigateway:latest

      - name: Build and Push eurekaserver Image
        uses: docker/build-push-action@v4
        with:
          context: ./eurekaServer
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/eurekaserver:latest

      - name: Build and Push roomservice Image
        uses: docker/build-push-action@v4
        with:
          context: ./roomService
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/roomservice:latest

      - name: Build and Push userservice Image
        uses: docker/build-push-action@v4
        with:
          context: ./userService
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/userservice:latest

      - name: Build and Push videoservice Image
        uses: docker/build-push-action@v4
        with:
          context: ./videoService
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/videoservice:latest
